name: Build Re:VIEW to make distribution file
# The workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Build Artifacts using Re:VIEW
      - name: Build distribution file
        uses: TechBooster/ReVIEW-build-artifact-action@master

      # Upload Distribution file to GitHub Artifacts
      - name: Upload distribution file to GitHub artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Output documents
          path: ./articles/*.pdf
